project = "UnitySemanticGraph"

[[gameObjects]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-484832227-0"
path = "Floor"
name = "Floor"
parent = ""

[[gameObjects]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-569126638-0"
path = "Floor/Cube"
name = "Cube"
parent = "Floor"
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-569126642-0"
type = "UnityEngine.MeshFilter"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-569126641-0"
type = "UnityEngine.MeshRenderer"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-569126640-0"
type = "UnityEngine.BoxCollider"
enabled = true

[[gameObjects]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-965996138-0"
path = "onCollide"
name = "onCollide"
parent = ""
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-965996140-0"
type = "ClusterVR.CreatorKit.Item.Implements.Item"
enabled = true
[gameObjects.components.properties]
Item_Name = ""
Size = [0, 0, 0]

[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-965996139-0"
type = "ClusterVR.CreatorKit.Item.Implements.ScriptableItem"
enabled = true
[gameObjects.components.properties]
Source_Code_Asset = "onCollideScript"
Source_Code = ""

[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-965996142-0"
type = "UnityEngine.Rigidbody"
enabled = true

[[gameObjects]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-287942458-0"
path = "onCollide/Cube"
name = "Cube"
parent = "onCollide"
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-287942462-0"
type = "UnityEngine.MeshFilter"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-287942461-0"
type = "UnityEngine.MeshRenderer"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-287942460-0"
type = "UnityEngine.BoxCollider"
enabled = true

[[gameObjects]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-1369298475-0"
path = "onGrab"
name = "onGrab"
parent = ""
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-1369298480-0"
type = "ClusterVR.CreatorKit.Item.Implements.Item"
enabled = true
[gameObjects.components.properties]
Item_Name = ""
Size = [0, 0, 0]

[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-1369298479-0"
type = "UnityEngine.Rigidbody"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-1369298478-0"
type = "ClusterVR.CreatorKit.Item.Implements.MovableItem"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-1369298477-0"
type = "ClusterVR.CreatorKit.Item.Implements.GrabbableItem"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-1369298476-0"
type = "ClusterVR.CreatorKit.Item.Implements.ScriptableItem"
enabled = true
[gameObjects.components.properties]
Source_Code_Asset = "onGrabScript"
Source_Code = ""


[[gameObjects]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-676474044-0"
path = "onGrab/Cube"
name = "Cube"
parent = "onGrab"
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-676474048-0"
type = "UnityEngine.MeshFilter"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-676474047-0"
type = "UnityEngine.MeshRenderer"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-676474046-0"
type = "UnityEngine.BoxCollider"
enabled = true

[[gameObjects]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-948913346-0"
path = "setPosition"
name = "setPosition"
parent = ""
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-948913349-0"
type = "ClusterVR.CreatorKit.Item.Implements.Item"
enabled = true
[gameObjects.components.properties]
Item_Name = ""
Size = [0, 0, 0]

[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-948913348-0"
type = "ClusterVR.CreatorKit.Item.Implements.ScriptableItem"
enabled = true
[gameObjects.components.properties]
Source_Code_Asset = "setPositionScript"
Source_Code = ""

[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-948913351-0"
type = "UnityEngine.Rigidbody"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-948913350-0"
type = "ClusterVR.CreatorKit.Item.Implements.MovableItem"
enabled = true

[[gameObjects]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-558795955-0"
path = "setPosition/Cube"
name = "Cube"
parent = "setPosition"
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-558795961-0"
type = "UnityEngine.MeshFilter"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-558795960-0"
type = "UnityEngine.MeshRenderer"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-558795959-0"
type = "UnityEngine.BoxCollider"
enabled = true

[[gameObjects]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-449583701-0"
path = "setRotation"
name = "setRotation"
parent = ""
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-449583704-0"
type = "ClusterVR.CreatorKit.Item.Implements.Item"
enabled = true
[gameObjects.components.properties]
Item_Name = ""
Size = [0, 0, 0]

[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-449583703-0"
type = "ClusterVR.CreatorKit.Item.Implements.ScriptableItem"
enabled = true
[gameObjects.components.properties]
Source_Code_Asset = "setRotationScript"
Source_Code = ""

[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-449583706-0"
type = "UnityEngine.Rigidbody"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-449583705-0"
type = "ClusterVR.CreatorKit.Item.Implements.MovableItem"
enabled = true

[[gameObjects]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-345345545-0"
path = "setRotation/Cube"
name = "Cube"
parent = "setRotation"
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-345345551-0"
type = "UnityEngine.MeshFilter"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-345345550-0"
type = "UnityEngine.MeshRenderer"
enabled = true
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-345345549-0"
type = "UnityEngine.BoxCollider"
enabled = true

[[gameObjects]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-927880994-0"
path = "System"
name = "System"
parent = ""

[[gameObjects]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-1376979812-0"
path = "System/Despawn Height"
name = "Despawn Height"
parent = "System"
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-1376979814-0"
type = "ClusterVR.CreatorKit.World.Implements.DespawnHeights.DespawnHeight"
enabled = true

[[gameObjects]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-1328207002-0"
path = "System/Directional Light"
name = "Directional Light"
parent = "System"
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-1328207003-0"
type = "UnityEngine.Light"
enabled = true

[[gameObjects]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-1641711191-0"
path = "System/Spawn Point"
name = "Spawn Point"
parent = "System"
[[gameObjects.components]]
id = "GlobalObjectId_V1-2-4623955290552cb4fb2bccad9a61aa7c-1641711193-0"
type = "ClusterVR.CreatorKit.World.Implements.SpawnPoints.SpawnPoint"
enabled = true
[gameObjects.components.properties]
Spawn_Type = "Entrance"
World_Gate_Key = ""


