name: ts-analyzer CI

on:
  push:
    paths:
      - 'packages/ts-analyzer/**'
  pull_request:
    paths:
      - 'packages/ts-analyzer/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: packages/ts-analyzer/package-lock.json

      - name: Install dependencies
        working-directory: packages/ts-analyzer
        # run: npm ci
        run: npm install

      - name: Build package
        working-directory: packages/ts-analyzer
        run: npm run build

      - name: Run tests
        working-directory: packages/ts-analyzer
        run: npm run test
